name: Run TestNG Tests

on:
  push:
    branches:
      - master    # Runs the workflow when code is pushed to the main branch
  pull_request:  # Runs the workflow for pull requests
    branches:
      - master 
  schedule:
    - cron: '0 19 * * *'  # Runs daily at 12:00 PM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Pulls the code from your GitHub repository

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'        # Specify your desired Java version
        distribution: 'temurin'   # Use OpenJDK distribution

    - name: Set Up Maven
      run: sudo apt-get install -y maven

    - name: Install Dependencies
      run: mvn clean install            # Installs dependencies from pom.xml

    - name: Run TestNG Tests
      run: mvn test               # Executes tests defined in testng.xml
