name: Run TestNG Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'   # run every 30 min

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check IST Time Window
      run: |
        HOUR=$(TZ="Asia/Kolkata" date +%H)
        if [ $HOUR -lt 9 ] || [ $HOUR -ge 19 ]; then
          echo "Skipping execution outside 9AM–7PM IST"
          exit 0
        fi

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # Or for Google Chrome:
        # wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        # sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        # sudo apt-get update && sudo apt-get install -y google-chrome-stable
        
    - name: Run TestNG Tests
      run: mvn -B clean test
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
