name: Run TestNG Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'   # run every 30 min

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check IST Time Window
      run: |
        HOUR=$(TZ="Asia/Kolkata" date +%H)
        if [ $HOUR -lt 9 ] || [ $HOUR -ge 19 ]; then
          echo "Skipping execution outside 9AM–7PM IST"
          exit 0
        fi

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run TestNG Tests
      run: mvn -B clean test
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
